### ISSUE TITLE
Milestone for Angular 5

### ISSUE THREAD

**Issue by mcgri** [MarkPieszak/aspnetcore-angular2-universal#516]
Hi

First of all, thank you for your effort bringing angular universal to .core ecosystem.
Could you please add a milestone for angular 5 migration? It will be easier to watch the progress of migration to angular 5...
Or at least, please provide a list of issues which should be closed before migration to angular 5 could happen.

Thank you

**Comment by MarkPieszak** [comment]
Sure! So Angular 5 was setup, but then there were some big production issues I didn't realize we'd face, some of the issues included:

 - [ ] Fix AngularCompilerPlugin to handle our use case
  - [ ] Get it to allow us to compile AoT on the fly correctly
 - [ ] Fix platform-server ServerTransferService to run before any other BEFORE_APP_SERIALIZE events
 - [ ] Test dev & prod workflows

Lastly the most important one is:

 - [ ] Move to Angular-CLI based template

It might be better for us to move towards that regardless, as it'll solve the above issues (since AngularCompilerPlugin for example was built with the CLI in mind, etc). 

A lot to think about :)

**Comment by MarkPieszak** [comment]
Waiting on ngtools/webpack PR to get merged and published here and this should allow us to upgrade back to Angular 5.x
angular/angular-cli#8951

**Comment by mcgri** [comment]
Good news:) can't wait... Christmas is comming :))

**Comment by Adondriel** [comment]
Oh man, moving to angular client is going to be fun. Does that mean we will be getting rid of webpack? Cause... I JUST finally got my head wrapped around how the hell that works! lol.

**Comment by Adondriel** [comment]
@MarkPieszak Will updating to Angular 5 fix the issue of not being able to have DOM elements be used in our code?

**Comment by MarkPieszak** [comment]
No you'll still not be able to use browser only APIs like `document.querySelector` / `navigator` or anything `window`, but you'll have access to `DOCUMENT` from common which is a server implementation of the Document, so if you use that, you can do querySelectors for example. But typically if you're trying to query things, there's probably a better more Angular way of doing it, so try to avoid that :)

**Comment by Adondriel** [comment]
Awesome, I'm trying to get https://github.com/swimlane/ngx-charts to work, and I just found out that their branch for updating to ng5, has the fix I'm gunna need, probably.

**Comment by jerkovicl** [comment]
Any ETA for those production issues?

**Comment by mcgri** [comment]
[angular/angular-cli#8951](https://github.com/angular/angular-cli/pull/8951) . was just approved..so hopefully the will merge it soon

**Comment by mcgri** [comment]
It takes ng team frustratingly long to merge the existing fix ~_~

**Comment by mcgri** [comment]
@MarkPieszak   they merge mentioned PR 🥇 . Our team needs to push code to production, urgently. how could we make a hot fix for aot bugs?

**Comment by odahcam** [comment]
I simply disabled AOT to don't lose SSR. It appears that we have to make a choice here, between AOT or SSR. :/

I think we should just track https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/482 and try to find a solution for that.

**Comment by mcgri** [comment]
I thought the fix from angular teams (https://github.com/angular/angular-cli/pull/8951) should allow compiling the AOT. Just general off topic l info, I disabled both SSR and AOT, and the system works on Azure with all kestrel goodies, so the pages loading in 800ms due to cache. The SSR and AOT will cut the script rendering times,which will reduce total loading times from 2sec to just 1..which is faster then Amazon (our system have more then 100 components :)) )

**Comment by odahcam** [comment]
I'm trying to discover if it was really fixed, but I got no responses.

**Comment by MarkPieszak** [comment]
The 5.0 version is fixed, I'm now merging the PR #538 into Master.
Take a look and let me know!

It's not totally perfect, but Production builds are finally possible.

Hopefully in a few weeks I'll have the transition to the CLI-based template in there, and we'll be in even better shape 👍
